<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INLH103689" ignored="0" name="Default test" tests="2" failures="1" timestamp="16 Sep 2019 05:34:11 GMT" time="288.144" errors="0">
  <testcase name="feature" time="157.88" classname="com.qa.Runner.TestRunner"/>
  <testcase name="feature" time="129.434" classname="com.qa.Runner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [private banking - rabobank] but found [contact opnemen met de rabobank – particulieren]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [private banking - rabobank] but found [contact opnemen met de rabobank – particulieren]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at com.qa.Runner.TestRunner.feature(TestRunner.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [private banking - rabobank] but found [contact opnemen met de rabobank – particulieren]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.Pages.Methods_ContactUs.VerifyPage_Title(Methods_ContactUs.java:26)
at com.qa.StepDefinitions.Steps_ContactUsPage.verify_the_ContactUs_Page_Details(Steps_ContactUsPage.java:33)
at ✽.Then Verify the ContactUs Page Details"Private Banking - Rabobank"(2_ContactUs.feature:19)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Default test -->
